Repository StarArawn/bevy_ecs_tilemap, pull requests merged in 2022-09, with the labels that each got.

#248 Set up basic CI
  .github/workflows/ci.yml
  .github/workflows/code_quality.yml
  .gitignore
  Cargo.lock
  Cargo.toml
  clippy.toml
  examples/helpers/tiled.rs
  src/render/texture_array_cache.rs
Labels: build system

#244 add support for render layers on tilemaps
  src/render/queue.rs
Labels: enhancement

#252 Add the ability to configure the chunk size.
  examples/chunking.rs
  src/map/mod.rs
  src/render/mod.rs
  src/render/prepare.rs
Labels: enhancement

#284 Fixed issue where atlas vertex/fragment shader failed to compile.
  src/render/shaders/tilemap_vertex.wgsl
  src/render/shaders/tilemap_vertex_output.wgsl
Labels: bug
